### ISSUE TITLE
How can it be used?

### ISSUE THREAD

**Issue by Hatko** [yakimovim/vscode-check-npm-updates#5]
I installed it, but it doesn't show any messages regarding obsolete dependencies. Neither by timer, or by calling it manually via command

**Comment by yakimovim** [comment]
The extension shows a message ONLY if it can find packages that can be updated. Otherwise, it shows nothing.

Regarding how it works:

It looks at the dependencies inside 'package.json' file. After that, it looks at the installed versions of these dependencies in the 'package-lock.json' file. After that, it looks at the available versions of these dependencies in the npm registry. Then the extension makes comparisons and displays messages if there are any dependencies that can be updated.

**Comment by Hatko** [comment]
`After that, it looks at the installed versions of these dependencies in the 'package-lock.json' file.`

So no yarn support?

**Comment by yakimovim** [comment]
No, no `yarn` support yet.

**Comment by yakimovim** [comment]
@Hatko , I have implemented support of Yarn.
